# Used Car Price Prediction

## 1) Problem statement.

* This dataset comprises used cars sold on cardehko.com in India as well as important features of these cars.
* If user can predict the price of the car based on input features.
* Prediction results can be used to give new seller the price suggestion based on market condition.

## 2) Data Collection.
* The Dataset is collected from scrapping from cardheko webiste
* The data consists of 13 column and 15411 rows.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [4]:
df = pd.read_csv("./cardekho_imputated.csv", index_col=[0])

In [5]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning
### Handling Missing values

* Handling Missing values
* Handling Duplicates
* Check data type
* Understand the dataset

In [6]:
## Check Null Values
##Check features with nan value
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [7]:
## Remove Unnecessary Columns
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

In [8]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [9]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [10]:
## Getting All Different Types OF Features
num_features = [feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features :', len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features :', len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features :',len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features :',len(continuous_features))

Num of Numerical Features : 7
Num of Categorical Features : 4
Num of Discrete Features : 2
Num of Continuous Features : 5

In [11]:
## Indpendent and dependent features
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

In [12]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Feature Encoding and Scaling
**One Hot Encoding for Columns which had lesser unique values and not ordinal**
* One hot encoding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in prediction.

In [13]:
len(df['model'].unique())

120

In [14]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [15]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
X['model']=le.fit_transform(X['model'])

In [16]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [17]:
len(df['seller_type'].unique()),len(df['fuel_type'].unique()),len(df['transmission_type'].unique())

(3, 5, 2)

In [18]:
# Create Column Transformer with 3 types of transformers
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type','fuel_type','transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder", oh_transformer, onehot_columns),
        ("StandardScaler", numeric_transformer, num_features)

    ],remainder='passthrough'

)

In [19]:
X=preprocessor.fit_transform(X)

In [20]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [21]:
# separate dataset into train and test
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2,random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [22]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

## Model Training And Model Selection

In [23]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [24]:
##Create a Function to Evaluate Model
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    mse = mean_squared_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)
    return mae, rmse, r2_square

In [25]:
## Beginning Model Training
models = {
    "Linear Regression": LinearRegression(),
    "Lasso": Lasso(),
    "Ridge": Ridge(),
    "K-Neighbors Regressor": KNeighborsRegressor(),
    "Decision Tree": DecisionTreeRegressor(),
    "Random Forest Regressor": RandomForestRegressor(),

}

for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    # Evaluate Train and Test dataset
    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)


    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Linear Regression
Model performance for Training set
- Root Mean Squared Error: 553855.6665
- Mean Absolute Error: 268101.6071
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502543.5930
- Mean Absolute Error: 279618.5794
- R2 Score: 0.6645
===================================


Lasso
Model performance for Training set
- Root Mean Squared Error: 553855.6710
- Mean Absolute Error: 268099.2226
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502542.6696
- Mean Absolute Error: 279614.7461
- R2 Score: 0.6645
===================================


Ridge
Model performance for Training set
- Root Mean Squared Error: 553856.3160
- Mean Absolute Error: 268059.8015
- R2 Score: 0.6218
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 502533.8230
- Mean Absolute Error: 279557.2169
- R2 Score: 0.6645
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 325885.9831
- Mean Absolute Error: 91430.9701
- R2 Score: 0.8691
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 253071.9428
- Mean Absolute Error: 112672.8917
- R2 Score: 0.9149
===================================


Decision Tree
Model performance for Training set
- Root Mean Squared Error: 20797.2352
- Mean Absolute Error: 5164.8199
- R2 Score: 0.9995
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 306936.1596
- Mean Absolute Error: 124662.8203
- R2 Score: 0.8749
===================================


Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 132977.2832
- Mean Absolute Error: 39798.3401
- R2 Score: 0.9782
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 225312.5454
- Mean Absolute Error: 101307.0654
- R2 Score: 0.9326
===================================

In [26]:
#Initialize few parameter for Hyperparamter tuning
knn_params = {"n_neighbors": [2, 3, 10, 20, 40, 50]}
rf_params = {"max_depth": [5, 8, 15, None, 10],
             "max_features": [5, 7, "auto", 8],
             "min_samples_split": [2, 8, 15, 20],
             "n_estimators": [100, 200, 500, 1000]}

In [27]:
# Models list for Hyperparameter tuning
randomcv_models = [('KNN', KNeighborsRegressor(), knn_params),
                   ("RF", RandomForestRegressor(), rf_params)

                   ]

In [28]:
##Hyperparameter Tuning
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
    random = RandomizedSearchCV(estimator=model,
                                   param_distributions=params,
                                   n_iter=100,
                                   cv=3,
                                   verbose=3,
                                   n_jobs=-1)
    random.fit(X_train, y_train)
    model_param[name] = random.best_params_

for model_name in model_param:
    print(f"---------------- Best Params for {model_name} -------------------")
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits

[CV 2/3] END .....................n_neighbors=2;, score=0.641 total time=   0.3s
[CV 1/3] END .....................n_neighbors=2;, score=0.865 total time=   0.3s
[CV 2/3] END ....................n_neighbors=10;, score=0.659 total time=   0.5s
[CV 1/3] END .....................n_neighbors=3;, score=0.855 total time=   0.3s
[CV 3/3] END .....................n_neighbors=2;, score=0.708 total time=   0.3s
[CV 2/3] END .....................n_neighbors=3;, score=0.678 total time=   0.4s
[CV 3/3] END ....................n_neighbors=10;, score=0.823 total time=   0.5s
[CV 3/3] END .....................n_neighbors=3;, score=0.779 total time=   0.4s
[CV 1/3] END ....................n_neighbors=10;, score=0.849 total time=   0.6s
[CV 1/3] END ....................n_neighbors=20;, score=0.828 total time=   0.8s
[CV 2/3] END ....................n_neighbors=20;, score=0.611 total time=   0.7s
[CV 3/3] END ....................n_neighbors=20;, score=0.776 total time=   0.9s
[CV 2/3] END ....................n_neighbors=40;, score=0.576 total time=   1.0s
[CV 1/3] END ....................n_neighbors=40;, score=0.812 total time=   1.1s
[CV 3/3] END ....................n_neighbors=40;, score=0.734 total time=   1.1s
[CV 1/3] END ....................n_neighbors=50;, score=0.800 total time=   1.1s
[CV 2/3] END ....................n_neighbors=50;, score=0.570 total time=   0.9s
[CV 3/3] END ....................n_neighbors=50;, score=0.723 total time=   0.8s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV 3/3] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200;, score=0.863 total time=   4.1s
[CV 2/3] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200;, score=0.732 total time=   4.3s
[CV 1/3] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000;, score=nan total time=   0.0s
[CV 2/3] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000;, score=nan total time=   0.0s
[CV 3/3] END max_depth=5, max_features=auto, min_samples_split=2, n_estimators=1000;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=200;, score=0.902 total time=   4.4s
[CV 2/3] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200;, score=0.763 total time=   8.9s
[CV 1/3] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200;, score=0.905 total time=   9.0s
[CV 2/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=500;, score=0.720 total time=   6.8s
[CV 1/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=500;, score=0.844 total time=   7.0s
[CV 3/3] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=200;, score=0.898 total time=   9.3s
[CV 1/3] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500;, score=nan total time=   0.0s
[CV 2/3] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500;, score=nan total time=   0.0s
[CV 3/3] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500;, score=nan total time=   0.0s
[CV 1/3] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 2/3] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 3/3] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=100;, score=nan total time=   0.0s
[CV 1/3] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100;, score=0.892 total time=   2.0s
[CV 3/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=500;, score=0.826 total time=   7.3s
[CV 2/3] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100;, score=0.764 total time=   2.0s
[CV 1/3] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.890 total time=  18.2s
[CV 3/3] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=100;, score=0.870 total time=   2.0s
[CV 3/3] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.866 total time=  18.3s
[CV 2/3] END max_depth=8, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.752 total time=  18.6s
[CV 1/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100;, score=0.837 total time=   1.4s
[CV 2/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100;, score=0.714 total time=   1.4s
[CV 3/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100;, score=0.810 total time=   1.6s
[CV 1/3] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=100;, score=0.903 total time=   2.6s
[CV 2/3] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=100;, score=0.752 total time=   2.6s
[CV 1/3] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100;, score=0.843 total time=   1.3s
[CV 3/3] END max_depth=None, max_features=5, min_samples_split=8, n_estimators=100;, score=0.884 total time=   2.6s
[CV 2/3] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100;, score=0.696 total time=   1.7s
[CV 1/3] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200;, score=nan total time=   0.0s
[CV 2/3] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200;, score=nan total time=   0.0s
[CV 3/3] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200;, score=nan total time=   0.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_split=20, n_estimators=100;, score=0.819 total time=   1.4s
[CV 1/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100;, score=0.892 total time=   2.3s
[CV 2/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100;, score=0.704 total time=   2.1s
[CV 1/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.819 total time=  11.8s
[CV 3/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100;, score=0.852 total time=   2.5s
[CV 1/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100;, score=0.886 total time=   2.2s
[CV 3/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.813 total time=  12.4s
[CV 2/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.703 total time=  12.8s
[CV 2/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100;, score=0.758 total time=   2.4s
[CV 3/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=100;, score=0.861 total time=   2.4s
[CV 1/3] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.907 total time=  31.7s
[CV 2/3] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.764 total time=  30.9s
[CV 3/3] END max_depth=15, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.880 total time=  31.6s
[CV 2/3] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.758 total time=  25.2s
[CV 1/3] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.902 total time=  25.9s
[CV 2/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.729 total time=  23.4s
[CV 1/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.893 total time=  25.5s
[CV 3/3] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000;, score=0.878 total time=  27.9s
[CV 1/3] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100;, score=0.843 total time=   2.5s
[CV 2/3] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100;, score=0.719 total time=   2.2s
[CV 1/3] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500;, score=0.903 total time=  15.9s
[CV 3/3] END max_depth=5, max_features=8, min_samples_split=8, n_estimators=100;, score=0.810 total time=   1.8s
[CV 1/3] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.908 total time=  44.7s
[CV 2/3] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.768 total time=  44.7s
[CV 1/3] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100;, score=0.898 total time=   2.3s
[CV 3/3] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=1000;, score=0.899 total time=  45.5s
[CV 2/3] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100;, score=0.739 total time=   2.5s
[CV 3/3] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100;, score=0.876 total time=   2.6s
[CV 1/3] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100;, score=0.894 total time=   2.7s
[CV 2/3] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500;, score=0.765 total time=  13.1s
[CV 2/3] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100;, score=0.741 total time=   2.9s
[CV 1/3] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100;, score=0.897 total time=   2.9s
[CV 2/3] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100;, score=0.731 total time=   3.0s
[CV 3/3] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=100;, score=0.867 total time=   2.9s
[CV 3/3] END max_depth=10, max_features=7, min_samples_split=20, n_estimators=100;, score=0.863 total time=   3.2s
[CV 3/3] END max_depth=10, max_features=7, min_samples_split=2, n_estimators=500;, score=0.894 total time=  16.1s
[CV 1/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200;, score=0.890 total time=   4.7s
[CV 2/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200;, score=0.728 total time=   4.4s
[CV 1/3] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100;, score=0.825 total time=   1.8s
[CV 3/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=200;, score=0.861 total time=   4.9s
[CV 2/3] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100;, score=0.681 total time=   1.7s
[CV 3/3] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=100;, score=0.805 total time=   2.3s
[CV 3/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.860 total time=  30.2s
[CV 2/3] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200;, score=0.757 total time=   9.2s
[CV 1/3] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200;, score=0.903 total time=   9.3s
[CV 3/3] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200;, score=0.879 total time=  10.0s
[CV 1/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100;, score=0.842 total time=   1.5s
[CV 2/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100;, score=0.713 total time=   1.5s
[CV 1/3] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000;, score=nan total time=   0.0s
[CV 2/3] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000;, score=nan total time=   0.0s
[CV 3/3] END max_depth=5, max_features=auto, min_samples_split=20, n_estimators=1000;, score=nan total time=   0.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100;, score=0.827 total time=   1.5s
[CV 2/3] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100;, score=0.751 total time=   2.7s
[CV 1/3] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100;, score=0.904 total time=   3.4s
[CV 2/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.721 total time=  21.3s
[CV 1/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.890 total time=  22.9s
[CV 3/3] END max_depth=15, max_features=5, min_samples_split=8, n_estimators=100;, score=0.882 total time=   3.6s
[CV 1/3] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200;, score=nan total time=   0.0s
[CV 2/3] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200;, score=nan total time=   0.0s
[CV 3/3] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200;, score=nan total time=   0.0s
[CV 1/3] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100;, score=0.909 total time=   4.0s
[CV 3/3] END max_depth=10, max_features=5, min_samples_split=20, n_estimators=1000;, score=0.859 total time=  23.3s
[CV 2/3] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100;, score=0.767 total time=   3.4s
[CV 3/3] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100;, score=0.901 total time=   3.5s
[CV 1/3] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200;, score=0.894 total time=   4.5s
[CV 2/3] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200;, score=0.726 total time=   4.2s
[CV 3/3] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200;, score=0.872 total time=   4.4s
[CV 1/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500;, score=0.908 total time=  25.1s
[CV 1/3] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200;, score=0.897 total time=   5.7s
[CV 1/3] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000;, score=nan total time=   0.0s
[CV 3/3] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=1000;, score=nan total time=   0.0s
[CV 2/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500;, score=0.763 total time=  25.3s
[CV 2/3] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200;, score=0.744 total time=   6.4s
[CV 3/3] END max_depth=10, max_features=8, min_samples_split=15, n_estimators=200;, score=0.870 total time=   6.8s
[CV 1/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200;, score=0.892 total time=   5.6s
[CV 2/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200;, score=0.725 total time=   5.9s
[CV 3/3] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=200;, score=0.857 total time=   5.7s
[CV 3/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500;, score=0.896 total time=  26.2s
[CV 1/3] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=100;, score=0.895 total time=   2.5s
[CV 2/3] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=100;, score=0.735 total time=   2.9s
[CV 3/3] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=100;, score=0.872 total time=   2.5s
[CV 1/3] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500;, score=0.886 total time=  10.4s
[CV 2/3] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500;, score=0.739 total time=   9.6s
[CV 1/3] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200;, score=nan total time=   0.0s
[CV 2/3] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200;, score=nan total time=   0.0s
[CV 3/3] END max_depth=None, max_features=auto, min_samples_split=20, n_estimators=200;, score=nan total time=   0.0s
[CV 1/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000;, score=0.842 total time=  19.7s
[CV 3/3] END max_depth=8, max_features=5, min_samples_split=8, n_estimators=500;, score=0.857 total time=   9.6s
[CV 2/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000;, score=0.718 total time=  19.2s
[CV 3/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000;, score=0.824 total time=  18.9s
[CV 1/3] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200;, score=0.889 total time=   3.3s
[CV 1/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500;, score=0.838 total time=   9.2s
[CV 2/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500;, score=0.704 total time=   9.5s
[CV 2/3] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200;, score=0.756 total time=   3.8s
[CV 3/3] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500;, score=0.813 total time=   9.4s
[CV 3/3] END max_depth=8, max_features=5, min_samples_split=2, n_estimators=200;, score=0.875 total time=   4.5s
[CV 1/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500;, score=0.889 total time=  13.2s
[CV 2/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500;, score=0.746 total time=  13.0s
[CV 3/3] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500;, score=0.859 total time=  12.9s
[CV 1/3] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500;, score=0.892 total time=  11.4s
[CV 1/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=200;, score=0.841 total time=   3.4s
[CV 2/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=200;, score=0.724 total time=   3.9s
[CV 3/3] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500;, score=0.876 total time=  11.9s
[CV 2/3] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500;, score=0.769 total time=  13.1s
[CV 1/3] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200;, score=nan total time=   0.0s
[CV 2/3] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200;, score=nan total time=   0.0s
[CV 3/3] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=200;, score=nan total time=   0.0s
[CV 1/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=200;, score=0.821 total time=   2.8s
[CV 3/3] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=200;, score=0.824 total time=   3.5s
[CV 2/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=200;, score=0.704 total time=   2.8s
[CV 3/3] END max_depth=5, max_features=5, min_samples_split=2, n_estimators=200;, score=0.812 total time=   2.6s
[CV 1/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100;, score=0.912 total time=   4.5s
[CV 3/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100;, score=0.889 total time=   5.4s
[CV 2/3] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=100;, score=0.778 total time=   6.1s
[CV 1/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000;, score=0.840 total time=  19.1s
[CV 2/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000;, score=0.717 total time=  18.0s
[CV 3/3] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000;, score=0.829 total time=  17.3s
[CV 1/3] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=1000;, score=0.893 total time=  25.1s
[CV 3/3] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500;, score=0.896 total time=  20.6s
[CV 1/3] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500;, score=0.909 total time=  21.6s
[CV 2/3] END max_depth=8, max_features=8, min_samples_split=2, n_estimators=1000;, score=0.762 total time=  25.9s
[CV 2/3] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=500;, score=0.774 total time=  21.5s

In [29]:
## Retraining the models with best parameters
models = {
    "Random Forest Regressor": RandomForestRegressor(n_estimators=100, min_samples_split=2, max_features='sqrt', max_depth=None,
                                                     n_jobs=-1),
     "K-Neighbors Regressor": KNeighborsRegressor(n_neighbors=10, n_jobs=-1)

}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(X_train, y_train) # Train model

    # Make predictions
    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae , model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)

    model_test_mae , model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(list(models.keys())[i])

    print('Model performance for Training set')
    print("- Root Mean Squared Error: {:.4f}".format(model_train_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_train_mae))
    print("- R2 Score: {:.4f}".format(model_train_r2))

    print('----------------------------------')

    print('Model performance for Test set')
    print("- Root Mean Squared Error: {:.4f}".format(model_test_rmse))
    print("- Mean Absolute Error: {:.4f}".format(model_test_mae))
    print("- R2 Score: {:.4f}".format(model_test_r2))

    print('='*35)
    print('\n')

Random Forest Regressor
Model performance for Training set
- Root Mean Squared Error: 150359.3791
- Mean Absolute Error: 40098.1069
- R2 Score: 0.9721
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 203665.0575
- Mean Absolute Error: 98232.6888
- R2 Score: 0.9449
===================================


K-Neighbors Regressor
Model performance for Training set
- Root Mean Squared Error: 363465.6927
- Mean Absolute Error: 103489.6090
- R2 Score: 0.8371
----------------------------------
Model performance for Test set
- Root Mean Squared Error: 263849.8119
- Mean Absolute Error: 117481.4548
- R2 Score: 0.9075
===================================